import TaskModel from './models/Task';
import type { Task } from '@piano-task-list/shared';

export async function seedDatabase() {
    await TaskModel.deleteMany({});

    const tasks: Omit<Task, 'id'>[] = [    // Omit id because generated by MongoDB
      {
        title: 'Buy groceries',
        description: 'Milk, eggs, bread'
      },
      {
        title: 'Clean the house',
        description: 'Vacuum and mop'
      },
    ];
  
    await TaskModel.insertMany(tasks);
    console.log('✅ Database seeded');
}